global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # File-based service discovery
  - job_name: 'dynamic-services'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/*.json'
          - '/etc/prometheus/targets/*.yml'
        refresh_interval: 30s
    scrape_interval: 30s
    metrics_path: /metrics