services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # 1.
      #- ./prometheus.yml:/etc/prometheus/prometheus.yml
      #- ./simple_rulefile.yml:/etc/prometheus/simple_rulefile.yml
      # 2. recording rule
      - ./prometheus-recordingrule.yml:/etc/prometheus/prometheus.yml
      - ./test-recording-rules.yaml:/etc/prometheus/test-recording-rules.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
