### 1. GET
GET {{PROMETHEUS_SERVER_HOST}}/api/v1/query?query=http_requests_total{job="apiserver"}

### 2. POST
POST {{PROMETHEUS_SERVER_HOST}}/api/v1/query
Content-Type: application/x-www-form-urlencoded

query=http_requests_total{job="apiserver"}