services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-test
    ports:
      - "9090:9090"
    volumes:
      - ./simple-test-prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'

  # Optional: Add a simple HTTP server to simulate targets
  fake-app:
    image: nginx:alpine
    container_name: fake-web-app
    ports:
      - "8080:80"
    
  # Optional: Node exporter for real metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-test
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'