global:
  scrape_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Simulate web services (you can replace with real targets)
  - job_name: 'web-app'
    static_configs:
      - targets: 
          - 'localhost:8080'  # Replace with real app or use fake target
          - 'localhost:8081'
    scrape_interval: 10s
    # If targets don't exist, they'll show as down but still create metrics

  # Simulate database (fake target for testing)
  - job_name: 'mysql-db'
    static_configs:
      - targets: ['localhost:3306']
    scrape_interval: 15s

  # Simulate infrastructure
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

# Simple recording rules to create job-level metrics for federation testing
rule_files:
  - "test_rules.yml"